spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
    hikari:
      minimumIdle: 1
      maximumPoolSize: 5
      idleTimeout: 30000
      poolName: inventory-api-conn-pool
      maxLifetime: 2000000
      connectionTimeout: 60000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
            naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
            dialect: org.hibernate.dialect.PostgreSQL9Dialect
            ddl-auto: validate     # Hibernate ddl auto (create, create-drop, validate, update)


#============================================================================
# DATABASE
db:
  name : inventory
  host : localhost
  port : 5432
  username : moka
  password : pgadmin
  auto-reconnect : true
  ssl : false

server:
  port: 8382


logging:
  level:
    org.apache.kafka : error